default: &default
  adapter: jdbcpostgresql
  database: crm_backend_development
  encoding: unicode
  username: vydeyaswanth
  password: '6174'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: crm_backend_development

test:
  <<: *default
  database: crm_backend_test

production:
  <<: *default
  database: crm_backend_production